// Posts do blog da Sampaio's (foco em síndicos, administradoras e empresas). Temas e textos diferentes do blog da
// LMT (lmt-site/src/data/blog.ts) para os sites não competirem com conteúdo duplicado.
// Blocos: "## " = subtítulo, "- " = item de lista, **negrito**, [texto](/link)

export const posts = [
  {
    slug: "manutencao-preventiva-esgoto-condominio",
    titulo: "Manutenção Preventiva de Esgoto em Condomínio",
    h1: "Manutenção Preventiva de Esgoto em Condomínio: o Calendário do Síndico",
    descricao: "O que entra na manutenção preventiva da rede de esgoto de um condomínio — prumadas, caixas de gordura, poço de recalque e reservatórios — e com que frequência.",
    resumo: "Prumadas, caixas de gordura, poço de recalque e reservatórios: o que fazer e com que frequência.",
    data: "2026-10-01",
    blocos: [
      "Em condomínio, o entupimento quase nunca acontece \"do nada\". Ele é o fim de um acúmulo de meses — de gordura na prumada da cozinha, de lodo no poço de recalque, de resíduo na caixa de inspeção. A manutenção preventiva existe justamente para tirar esse acúmulo antes que ele vire emergência de madrugada, com esgoto voltando no apartamento do térreo.",
      "## O que entra na manutenção",
      "- **Caixas de gordura coletivas:** recebem a gordura das pias de todos os apartamentos. Sem limpeza, o cheiro sobe pelos ralos da área comum e a prumada da cozinha entope.",
      "- **Prumadas e coletores:** as tubulações verticais que descem de cada andar e o coletor do térreo ou subsolo. O [hidrojateamento](/hidrojateamento) limpa toda a parede do cano, não só o ponto entupido.",
      "- **Caixas de inspeção:** os pontos de acesso da rede, onde o resíduo se acumula e onde o problema é diagnosticado.",
      "- **Poço de recalque:** em prédios com subsolo, o esgoto que fica abaixo do nível da rua é bombeado. O poço acumula lodo e precisa de esgotamento periódico com caminhão de sucção.",
      "- **Reservatórios de água:** não são esgoto, mas entram no mesmo calendário — a [limpeza da caixa d'água](/limpeza-de-caixa-dagua) é recomendada a cada 6 meses.",
      "## Uma frequência de referência",
      "Cada prédio tem seu ritmo, que depende do número de unidades, da idade da rede e do histórico de chamados. Como ponto de partida:",
      "- **Caixas de gordura coletivas:** a cada 2 a 3 meses (mensal se o prédio tem restaurante no térreo).",
      "- **Poço de recalque:** a cada 6 meses, com teste das bombas.",
      "- **Hidrojateamento das prumadas da cozinha:** uma vez por ano.",
      "- **Reservatórios de água:** a cada 6 meses.",
      "O histórico de chamados é o melhor ajuste: se a mesma prumada entope duas vezes no ano, a frequência dela precisa aumentar.",
      "## Por que vale a pena",
      "Uma emergência à noite ou no fim de semana custa mais, tira moradores de casa e pode danificar apartamentos — e a conta do conserto do apartamento atingido costuma voltar para o condomínio. Com a preventiva, o serviço é marcado, os moradores são avisados e o custo é previsível.",
      "## Documentação",
      "Peça à empresa um comprovante de cada serviço, com data e o que foi feito. Esse histórico ajuda na prestação de contas da assembleia, na troca de síndico e em eventuais discussões com a seguradora.",
      "A Sampaio's monta contratos de manutenção para condomínios, com atendimento prioritário 24 horas e nota fiscal. [Veja as regiões atendidas](/regioes-atendidas).",
    ],
  },
  {
    slug: "caixa-de-gordura-restaurante-fiscalizacao",
    titulo: "Caixa de Gordura de Restaurante e Fiscalização",
    h1: "Caixa de Gordura de Restaurante: Frequência de Limpeza e o que a Fiscalização Pede",
    descricao: "Com que frequência limpar a caixa de gordura de restaurante, lanchonete ou padaria, quais documentos guardar e como evitar entupimento no horário de pico.",
    resumo: "Frequência de limpeza, documentos para guardar e como evitar entupimento no meio do serviço.",
    data: "2026-10-01",
    blocos: [
      "Para quem tem restaurante, lanchonete, padaria ou cozinha industrial, a caixa de gordura não é detalhe de manutenção: é o ponto que, se falhar, para a cozinha no meio do serviço e espalha cheiro de esgoto pelo salão.",
      "## Com que frequência limpar",
      "Depende do volume de fritura e de louça, mas a referência para cozinha comercial é:",
      "- **Restaurantes e lanchonetes com movimento:** limpeza mensal.",
      "- **Cozinhas industriais e fast-food de alto volume:** a cada 15 dias ou semanalmente.",
      "- **Cafeterias e cozinhas de baixo volume:** a cada 2 meses.",
      "Um sinal simples de que a frequência está baixa: a caixa já está com a camada de gordura cobrindo a superfície inteira quando a equipe chega.",
      "## O que a fiscalização costuma olhar",
      "A vigilância sanitária e os órgãos ambientais podem pedir comprovação de que a caixa é limpa com regularidade e de que o resíduo teve destinação correta — gordura de caixa não pode ir para o lixo comum nem para a rede de esgoto. Por isso, guarde:",
      "- **Comprovante de cada limpeza**, com data.",
      "- **Nota fiscal do serviço.**",
      "- **Informação de destinação do resíduo** fornecida pela empresa contratada.",
      "## Como evitar entupimento no horário de pico",
      "- **Agende a limpeza** para o horário em que a cozinha está parada (manhã cedo ou depois do fechamento).",
      "- **Raspe os pratos no lixo** antes da lavagem; resto de comida acelera o enchimento da caixa.",
      "- **Óleo de fritura usado** vai para coleta de reciclagem, nunca para a pia.",
      "- **Use ralos com cesto** nas pias de lavagem.",
      "- Se a caixa enche rápido demais mesmo com limpeza mensal, ela pode ser pequena para o volume atual da cozinha — vale avaliar a troca.",
      "## Quando a caixa grande não dá para limpar à mão",
      "Caixas de grande volume e caixas separadoras de cozinhas industriais são esgotadas com caminhão de sucção, que retira todo o conteúdo sem contato manual e leva o resíduo para destinação licenciada.",
      "A Sampaio's faz [limpeza de caixa de gordura](/limpeza-de-caixa-de-gordura) programada para restaurantes e empresas, com comprovante e nota fiscal.",
    ],
  },
  {
    slug: "poco-de-recalque-sinais-e-manutencao",
    titulo: "Poço de Recalque: Sinais e Manutenção",
    h1: "Poço de Recalque de Esgoto: Sinais de Problema e Como Evitar Pane",
    descricao: "Como funciona o poço de recalque de esgoto do prédio, os sinais de que algo está errado (alarme, cheiro, bomba ligando sem parar) e a manutenção que evita pane.",
    resumo: "Como funciona, os sinais de alerta e a manutenção que evita esgoto no subsolo.",
    data: "2026-10-01",
    blocos: [
      "Em prédios com subsolo, parte do esgoto fica abaixo do nível da rede da rua e não consegue sair por gravidade. Ele cai em um poço — o poço de recalque — e de lá é bombeado para cima, até a rede. Quando o poço falha, o esgoto sobe no subsolo, na garagem ou nas áreas de lazer.",
      "## Como funciona",
      "O poço tem duas bombas (uma reserva da outra) e boias que ligam e desligam as bombas conforme o nível sobe. Em muitos prédios há também um alarme de nível alto, que dispara quando o esgoto passa do limite.",
      "## Sinais de que algo está errado",
      "- **Alarme de nível alto** disparando.",
      "- **Bomba ligando e desligando sem parar**, ou funcionando o tempo todo.",
      "- **Cheiro forte de esgoto** no subsolo ou na garagem.",
      "- **Ralos do subsolo voltando** ou água no piso perto do poço.",
      "- **Barulho diferente** nas bombas.",
      "## As causas mais comuns",
      "- **Lenços umedecidos, absorventes e fio dental** descartados no vaso: não se desfazem e enroscam no rotor das bombas.",
      "- **Gordura** que escapa das caixas de gordura e forma placas no poço.",
      "- **Boia travada** por sujeira, que não liga a bomba na hora certa.",
      "- **Lodo acumulado** no fundo, reduzindo o volume útil do poço.",
      "## A manutenção que evita pane",
      "- **Esgotamento e limpeza do poço** com caminhão de sucção, em geral a cada 6 meses.",
      "- **Teste das duas bombas**, alternando o funcionamento para a reserva não travar parada.",
      "- **Limpeza e teste das boias** e do alarme.",
      "- **Aviso aos moradores** sobre o que não jogar no vaso — é a medida mais barata de todas.",
      "## Se o alarme disparar",
      "Peça aos moradores para evitar descargas e banhos até a situação ser resolvida, verifique se o disjuntor das bombas está ligado e chame atendimento de emergência. A Sampaio's atende 24 horas com [caminhão de sucção](/limpa-fossa) e equipe para [desentupimento de esgoto](/desentupimento-de-esgoto).",
    ],
  },
  {
    slug: "ramal-de-esgoto-responsabilidade",
    titulo: "Entupimento no Ramal: de Quem É a Responsabilidade",
    h1: "Entupimento no Ramal de Esgoto: a Responsabilidade é do Imóvel ou da Concessionária?",
    descricao: "Entenda até onde vai a responsabilidade do imóvel e onde começa a da concessionária de saneamento quando o esgoto entope entre a casa e a rua.",
    resumo: "Até onde vai a rede do imóvel e quando acionar a concessionária de saneamento.",
    data: "2026-10-01",
    blocos: [
      "Quando o esgoto entope perto da calçada, a primeira dúvida é: quem resolve? A resposta depende de onde exatamente está o entupimento — e saber disso evita pagar por um serviço que é da concessionária, ou esperar dias por uma visita que não vai resolver.",
      "## As três partes do caminho do esgoto",
      "- **Instalação interna:** todos os canos, ralos e caixas dentro do imóvel, até a caixa de inspeção mais próxima da rua. É responsabilidade do proprietário (ou do condomínio, nas áreas comuns).",
      "- **Ramal predial:** o trecho que liga o imóvel à rede da rua, passando por baixo da calçada.",
      "- **Rede coletora pública:** a tubulação que passa na rua e recebe o esgoto de todos os imóveis.",
      "Em geral, a rede pública e a ligação até a rede são de responsabilidade da concessionária (na capital, a Sabesp), enquanto tudo o que está dentro do lote é do proprietário. A regra exata de onde termina um e começa o outro varia por concessionária — vale confirmar com a da sua cidade.",
      "## Como descobrir onde está o entupimento",
      "- **Abra a caixa de inspeção mais próxima da rua.** Se ela está cheia, o entupimento está depois dela — no ramal ou na rede pública.",
      "- **Se ela está vazia** e o esgoto volta dentro do imóvel, o problema está na instalação interna.",
      "- **Vizinhos com o mesmo problema** indicam entupimento na rede pública.",
      "## Quando chamar a concessionária",
      "Se a caixa de inspeção da frente está cheia e os vizinhos também estão com problema, acione a concessionária de saneamento. Em caso de esgoto extravasando na rua, informe isso no chamado — costuma ter prioridade.",
      "## Quando chamar uma desentupidora",
      "Se o problema está dentro do imóvel, ou se a concessionária já esteve no local e confirmou que a rede pública está livre, é hora do [desentupimento de esgoto](/desentupimento-de-esgoto) particular. Uma desentupidora séria também diz quando o problema não é dela: se a equipe chega e vê que o entupimento está na rede pública, o certo é orientar você a acionar a concessionária.",
      "A Sampaio's faz a avaliação sem cobrar a visita e atende 24 horas em [São Paulo, Grande SP e interior](/regioes-atendidas).",
    ],
  },
];
